exclude: ^tests/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: mixed-line-ending
  - id: end-of-file-fixer
- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
    - id: flake8
      args: ["--extend-ignore=E203,E501", "--per-file-ignores=__init__.py:F401"]
- repo: https://github.com/pycqa/bandit
  rev: 1.7.9
  hooks:
    - id: bandit
      args: [ --exclude, tests ]
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
    - id: black
- repo: https://github.com/pre-commit/mirrors-mypy/
  rev: "v1.11.1"
  hooks:
    - id: mypy
- repo: local
  hooks:
  - id: run-tests
    name: run tests
    entry: .venv/bin/pytest
    language: system
    always_run: true
    pass_filenames: false
  - id: check-coverage
    name: Check Coverage
    entry: .venv/bin/python tests/test_coverage.py
    language: python
    always_run: true
